[AmgX] nvtx -> nvtx3 to support Cuda 12.9

diff --git a/ThirdPart/src/LIBAMGX/install b/ThirdPart/src/LIBAMGX/install
--- a/ThirdPart/src/LIBAMGX/install
+++ b/ThirdPart/src/LIBAMGX/install
@@ -47,12 +47,16 @@ then
    AMGX_COMPILERS="-DCMAKE_CXX_COMPILER=$TRUST_CC_BASE -DCMAKE_C_COMPILER=$TRUST_cc_BASE -DCMAKE_CXX_FLAGS=-std=c++14"
    AMGX_COMPILERS=$AMGX_COMPILERS" -DCMAKE_CXX_FLAGS=-fno-openmp" # Important de specifier car AmgX cherche OpenMP par defaut
    # Ajout de l'architecture:
+   # Attention, ne pas forcer TRUST_CUDA_CC=80 sur H100 !!! Crash thrust failure sur bench OpenMP_Iterateur par exemple.
    [ "${TRUST_CUDA_CC#7}" != "$TRUST_CUDA_CC" ] && TRUST_CUDA_CC=70 # Volta
    [ "${TRUST_CUDA_CC#8}" != "$TRUST_CUDA_CC" ] && TRUST_CUDA_CC=80 # Ampere
    AMGX_COMPILERS=$AMGX_COMPILERS" -DCUDA_ARCH=$TRUST_CUDA_CC"
    
    # Hack du CMakeLists.txt (vu sur orcus avec Cuda 12) car manque de cublasLt
    sed -i "1,$ s?CUDA::cublas?CUDA::cublas CUDA::cublasLt?g" ../CMakeLists.txt || exit -1
+   # Switch to nvtx3 with Cuda >= 12.9 cause nvtx deprecated
+   sed -i "1,$ s?CUDA::nvToolsExt??g" ../CMakeLists.txt || exit -1
+   sed -i "1,$ s?nvToolsExt.h?nvtx3/nvToolsExt.h?g" ../include/amgx_timer.h || exit -1
    
    if [ "$HOST" = jean-zay ]
    then
